### ISSUE TITLE
[Bug]: Not working mods

### ISSUE THREAD

**Issue by h6rake** [Kynomi/SD2MC#20]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

[image](https://user-images.githubusercontent.com/130908695/232312197-d529c996-3804-45fd-ba18-21a3da6e7f43.png) every time whem im tryin' to make any mods 

### Input here what items did you try to create

```shell
Master of the Searing Path Belt or any other set on ember/queen of pain
```

### Email, discord, telegram or vk

hellroyale123@gmail.com

**Comment by Kynomi** [comment]
I fixed this bug. Update script. Thank you for bug report!
