### ISSUE TITLE
[Bug]: Не удаётся создать мод

### ISSUE THREAD

**Issue by SD1J** [Kynomi/SD2MC#21]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

В ПРОШЛОЙ ВЕРСИИ МОЖНО БЫЛО СОЗДАТЬ СЕТ ИЗ КОЛЕКТОРКИ. НАПРИМЕР СЕТ НА СФА SOULS TYRANT, НО СЕЙЧАС ЕГО СОЗДАТЬ НЕЛЬЗЯ.

ВЫДАЁТ ЭТУ ОШИБКУ

![image](https://user-images.githubusercontent.com/76493743/232330650-60406895-15d9-47ee-9281-00ce8f8d1644.png)

### Input here what items did you try to create

```shell
Shadow Fiend's Head
Souls Tyrant Head
```

**Comment by Kynomi** [comment]
Вы отметили галочку  I have searched the existing issues даже не посмотрев закрытые обсуждения? Уже исправил эту ошибку, обновите скрипт.
