### ISSUE TITLE
[Bug]: Error

### ISSUE THREAD

**Issue by DLNATE** [Kynomi/SD2MC#24]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Такая ошибка возникает при создании некоторых сетов или отдельных шмоток:
![dota2_8RSyYfRNuB](https://github.com/Kynomi/SD2MC/assets/112611768/7fb2a83f-e16b-4401-89ce-1dee5190526d)
Искал в баг репортах, примерно такая же ошибка была, но решения не было

### Input here what items did you try to create

```shell
Morpling: Darktrench Stalker - Arms; Darktrench Stalker - Back; Darktrench Stalker - Head; Darktrench Stalker - Misc; Darktrench Stalker - Shoulder; Blade of Tears
Juggernaut: Provocation of Ruin Ward; Fortune's Tout
```

### Email, discord, telegram or vk

dis: dlnate

**Comment by luma-vpk** [comment]
проблема в скриптах то

**Comment by Kynomi** [comment]
You can't create modification for morphling
