### ISSUE TITLE
[Bug]: не создается мод

### ISSUE THREAD

**Issue by luma-vpk** [Kynomi/SD2MC#25]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

застакалось создание мода
![image](https://github.com/Kynomi/SD2MC/assets/94155195/a87ba3bb-d923-43cf-a51b-d6ec439f49cd)

### Input here what items did you try to create

```shell
Blades of Voth Domosh
```

### Email, discord, telegram or vk

tg: @wuquta

**Comment by Kynomi** [comment]
Только что проверил, мод отлично создается, не знаю, в чем ваша проблема.
