### ISSUE TITLE
[Bug]: не создается мод

### ISSUE THREAD

**Issue by vaskakiller228** [Kynomi/SD2MC#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Не создается мод, нажимаю кнопку и ничего не происходит(дело не в стиле, я делал и с ним и без него)

![4A0Q2Kh8ZK](https://github.com/Kynomi/SD2MC/assets/137224323/910b2c9d-adc3-4370-b11a-6f6ae4f6d7a7)

### Input here what items did you try to create

```shell
Terrorblade's Head
Fractal Horns of Inner Abysm
```

### Email, discord, telegram or vk

vaskakiller228 tg

**Comment by Kynomi** [comment]
Вы нажимаете не ту кнопку, там прям написано "Создать модификации"

**Comment by vaskakiller228** [comment]
у меня не создавался мод потому-что я не ту вкладку выбрал, я выбрал изменение конфигурации модификации, я еблан
